[2025-09-24T21:22:33.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-24T21:22:33.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecom_etl.transform_load_postgres manual__2025-09-24T21:22:14.477908+00:00 [queued]>
[2025-09-24T21:22:33.548+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecom_etl.transform_load_postgres manual__2025-09-24T21:22:14.477908+00:00 [queued]>
[2025-09-24T21:22:33.550+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-24T21:22:33.566+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): transform_load_postgres> on 2025-09-24 21:22:14.477908+00:00
[2025-09-24T21:22:33.571+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2025-09-24T21:22:33.575+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecom_etl', 'transform_load_postgres', 'manual__2025-09-24T21:22:14.477908+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ecom_etl_dag.py', '--cfg-path', '/tmp/tmp8oa1lkw7']
[2025-09-24T21:22:33.577+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask transform_load_postgres
[2025-09-24T21:22:33.640+0000] {task_command.py:426} INFO - Running <TaskInstance: ecom_etl.transform_load_postgres manual__2025-09-24T21:22:14.477908+00:00 [running]> on host b829da94a7fc
[2025-09-24T21:22:33.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ecom' AIRFLOW_CTX_DAG_ID='ecom_etl' AIRFLOW_CTX_TASK_ID='transform_load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T21:22:14.477908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T21:22:14.477908+00:00'
[2025-09-24T21:22:33.736+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-24T21:22:33.757+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-24T21:22:33.759+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PG_HOST=postgres PG_USER=ecom_user PG_PASS=ecom_pass PG_DB=ecom_dw PG_SCHEMA=ecom;python /opt/airflow/scripts/transform_load_postgres.py']
[2025-09-24T21:22:33.768+0000] {subprocess.py:86} INFO - Output:
[2025-09-24T21:23:05.767+0000] {subprocess.py:93} INFO - Reading from MongoDB ...
[2025-09-24T21:23:05.768+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-24T21:23:05.768+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/transform_load_postgres.py", line 49, in <module>
[2025-09-24T21:23:05.769+0000] {subprocess.py:93} INFO -     df_cust   = mongo_to_df("customers")
[2025-09-24T21:23:05.770+0000] {subprocess.py:93} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.770+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/transform_load_postgres.py", line 46, in mongo_to_df
[2025-09-24T21:23:05.771+0000] {subprocess.py:93} INFO -     return pd.DataFrame(list(cur))
[2025-09-24T21:23:05.772+0000] {subprocess.py:93} INFO -                         ^^^^^^^^^
[2025-09-24T21:23:05.772+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/cursor.py", line 1289, in __next__
[2025-09-24T21:23:05.772+0000] {subprocess.py:93} INFO -     return self.next()
[2025-09-24T21:23:05.773+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-09-24T21:23:05.773+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/cursor.py", line 1265, in next
[2025-09-24T21:23:05.773+0000] {subprocess.py:93} INFO -     if len(self._data) or self._refresh():
[2025-09-24T21:23:05.773+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.774+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/cursor.py", line 1213, in _refresh
[2025-09-24T21:23:05.774+0000] {subprocess.py:93} INFO -     self._send_message(q)
[2025-09-24T21:23:05.774+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/cursor.py", line 1108, in _send_message
[2025-09-24T21:23:05.775+0000] {subprocess.py:93} INFO -     response = client._run_operation(
[2025-09-24T21:23:05.775+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.775+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
[2025-09-24T21:23:05.775+0000] {subprocess.py:93} INFO -     return func(self, *args, **kwargs)
[2025-09-24T21:23:05.776+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.776+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 1938, in _run_operation
[2025-09-24T21:23:05.776+0000] {subprocess.py:93} INFO -     return self._retryable_read(
[2025-09-24T21:23:05.777+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.777+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2047, in _retryable_read
[2025-09-24T21:23:05.777+0000] {subprocess.py:93} INFO -     return self._retry_internal(
[2025-09-24T21:23:05.778+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.778+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
[2025-09-24T21:23:05.778+0000] {subprocess.py:93} INFO -     return func(self, *args, **kwargs)
[2025-09-24T21:23:05.779+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.779+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2014, in _retry_internal
[2025-09-24T21:23:05.779+0000] {subprocess.py:93} INFO -     ).run()
[2025-09-24T21:23:05.780+0000] {subprocess.py:93} INFO -       ^^^^^
[2025-09-24T21:23:05.780+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2765, in run
[2025-09-24T21:23:05.780+0000] {subprocess.py:93} INFO -     return self._read() if self._is_read else self._write()
[2025-09-24T21:23:05.781+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^
[2025-09-24T21:23:05.781+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2910, in _read
[2025-09-24T21:23:05.781+0000] {subprocess.py:93} INFO -     self._server = self._get_server()
[2025-09-24T21:23:05.782+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.782+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2858, in _get_server
[2025-09-24T21:23:05.782+0000] {subprocess.py:93} INFO -     return self._client._select_server(
[2025-09-24T21:23:05.783+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.783+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 1833, in _select_server
[2025-09-24T21:23:05.783+0000] {subprocess.py:93} INFO -     server = topology.select_server(
[2025-09-24T21:23:05.784+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.784+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 409, in select_server
[2025-09-24T21:23:05.785+0000] {subprocess.py:93} INFO -     server = self._select_server(
[2025-09-24T21:23:05.785+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.785+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 387, in _select_server
[2025-09-24T21:23:05.785+0000] {subprocess.py:93} INFO -     servers = self.select_servers(
[2025-09-24T21:23:05.786+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.786+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 294, in select_servers
[2025-09-24T21:23:05.786+0000] {subprocess.py:93} INFO -     server_descriptions = self._select_servers_loop(
[2025-09-24T21:23:05.786+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-24T21:23:05.787+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/topology.py", line 344, in _select_servers_loop
[2025-09-24T21:23:05.787+0000] {subprocess.py:93} INFO -     raise ServerSelectionTimeoutError(
[2025-09-24T21:23:05.787+0000] {subprocess.py:93} INFO - pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68d4611b16cf9307631428f3, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-09-24T21:23:06.413+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-24T21:23:06.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-24T21:23:06.422+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-24T21:23:06.428+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecom_etl, task_id=transform_load_postgres, run_id=manual__2025-09-24T21:22:14.477908+00:00, execution_date=20250924T212214, start_date=20250924T212233, end_date=20250924T212306
[2025-09-24T21:23:06.441+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task transform_load_postgres (Bash command failed. The command returned a non-zero exit code 1.; 511)
[2025-09-24T21:23:06.450+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-24T21:23:06.465+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T21:23:06.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
